spring:
  application:
    #微服务名称，名字中不要出现下划线“_”，否则在使用Feign时会报错
    name: service-client1

server:
  #服务开放端口
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/